# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89d8b8e6ccc3de405858e66c42fe258daaba4de11f1d606f07bd3b6f8a79070aa1c19399d66a76252a415e8e1add4044294de5664a726c97a519f3ab472ad7b4

test:
  secret_key_base: 59e83a1e47b32d79bd6d7130ee3b644cf73de3abb565cde3ddd080abde6220593aae7b4e755ae2501d66448fa7edeb270be4d0916461bf34fc7fb08ce3f4384b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
